# Makefile For Project Submission
#

simple_server_objects = ServerSocket.o Socket.o server.o
simple_client_objects = ClientSocket.o Socket.o client.o


all : server client

server: $(simple_server_objects)
	g++ -o server $(simple_server_objects)


client: $(simple_client_objects)
	g++ -o client $(simple_client_objects)


Socket: Socket.cpp
ServerSocket: ServerSocket.cpp
ClientSocket: ClientSocket.cpp
server: server.cpp
client: client.cpp


clean:
	rm -f *.o server client